// Premiere Pro ExtendScript API Reference for LLM consumption
// Exported as a plain string constant

export const EXTENDSCRIPT_REFERENCE = [
  "# Premiere Pro ExtendScript API Reference (ES3 Syntax)",
  "",
  "## CRITICAL: ES3 Rules",
  "- Use \"var\" not \"let/const\"",
  "- No arrow functions: use \"function(x) { return x; }\"",
  "- No template literals: use string concatenation \"a\" + \"b\"",
  "- No destructuring: use obj.prop instead of {prop} = obj",
  "- No for...of: use indexed for loops",
  "",
  "## Core Objects",
  "app.project                    - ProjectBase (the current project)",
  "app.project.activeSequence     - Sequence (currently active)",
  "app.project.rootItem           - ProjectItem (root bin)",
  "app.project.sequences          - SequenceCollection (.numSequences, [i])",
  "app.version                    - String (Premiere version)",
  "app.sourceMonitor              - SourceMonitor",
  "app.encoder                    - Encoder",
  "",
  "## Project Methods",
  "app.project.save()",
  "app.project.saveAs(path)",
  "app.project.importFiles(pathsArray, suppressUI, targetBin, asNumberedStills)",
  "app.project.importAEComps(aepPath, compNamesArray, targetBin)",
  "app.project.importAllAEComps(aepPath, targetBin)",
  "app.project.createNewSequence(name, placeholderID)",
  "app.project.createNewSequenceFromClips(name, clipItemsArray)",
  "app.project.consolidateDuplicates()",
  "app.project.addPropertyToProjectMetadataSchema(name, label, type)",
  "app.project.undo()",
  "app.newProject(path)",
  "app.openDocument(path)",
  "",
  "## ProjectItem (clips/bins in project panel)",
  "item.nodeId                    - String (unique identifier)",
  "item.name                      - String",
  "item.type                      - Number (1=clip/file, 2=bin, 3=root, 4=file)",
  "item.treePath                  - String",
  "item.children                  - ProjectItemCollection (.numItems, [i])",
  "item.getMediaPath()            - String (file path on disk)",
  "item.changeMediaPath(newPath, overrideChecks)",
  "item.refreshMedia()",
  "item.moveBin(targetBin)",
  "item.deleteBin()",
  "item.renameBin(newName)",
  "item.createBin(name)           - ProjectItem (new bin)",
  "item.createSmartBin(name, query)",
  "item.createSubClip(name, startTicks, endTicks, hasHardBoundaries, takeVideo, takeAudio)",
  "item.setInPoint(ticks, mediaType)",
  "item.setOutPoint(ticks, mediaType)",
  "item.getInPoint(mediaType)     - Time",
  "item.getOutPoint(mediaType)    - Time",
  "item.setOverridePixelAspectRatio(num, den)",
  "item.setOverrideFrameRate(fps)",
  "item.attachProxy(mediaPath, isHiRes)",
  "item.findItemsMatchingMediaPath(pathQuery)  - Array",
  "item.canChangeMediaPath()      - Boolean",
  "item.isOffline()               - Boolean",
  "item.setStartTime(ticks)",
  "item.setColorLabel(colorIndex)  - 0-15",
  "item.getColorLabel()           - Number",
  "item.getProjectMetadata()      - String (XML)",
  "item.setProjectMetadata(xmlStr, fieldPath)",
  "",
  "## Sequence",
  "seq.name                       - String",
  "seq.sequenceID                 - String",
  "seq.videoTracks                - TrackCollection (.numTracks, [i])",
  "seq.audioTracks                - TrackCollection (.numTracks, [i])",
  "seq.markers                    - MarkerCollection",
  "seq.end                        - String (ticks)",
  "seq.frameSizeHorizontal        - Number",
  "seq.frameSizeVertical          - Number",
  "",
  "seq.insertClip(projectItem, startTicks, vidTrackIdx, audioTrackIdx)",
  "seq.overwriteClip(projectItem, startTicks, vidTrackIdx, audioTrackIdx)",
  "seq.getPlayerPosition()        - Time",
  "seq.setPlayerPosition(ticks)",
  "seq.setInPoint(ticks)",
  "seq.setOutPoint(ticks)",
  "seq.getInPoint()               - String (ticks)",
  "seq.getOutPoint()              - String (ticks)",
  "seq.setWorkAreaInPoint(ticks)",
  "seq.setWorkAreaOutPoint(ticks)",
  "seq.setZeroPoint(ticks)",
  "seq.close()",
  "seq.clone()                    - Sequence",
  "seq.linkSelection()",
  "seq.unlinkSelection()",
  "seq.getSelection()             - Array of TrackItems",
  "seq.exportAsProject(path)",
  "seq.exportAsFinalCutProXML(path, suppressUI)",
  "seq.exportAsMediaDirect(outputPath, presetPath, workAreaType)",
  "seq.getExportFileExtension(presetPath)",
  "seq.autoReframeSequence(numerator, denominator, motionPreset, newName, useNestedSequences)",
  "seq.performSceneEditDetectionOnSelection()",
  "seq.createSubsequence(selectionOnly)",
  "seq.addTracks(videoTracksToAdd, audioTracksToAdd)",
  "",
  "## Track",
  "track.name                     - String",
  "track.clips                    - ClipCollection (.numItems, [i])",
  "track.transitions              - TransitionCollection (.numItems, [i])",
  "track.isMuted()                - Boolean",
  "track.setMute(muted)",
  "track.isLocked()               - Boolean",
  "track.setLocked(locked)",
  "track.isTargeted()             - Boolean",
  "track.setTargeted(targeted, isVideo)",
  "track.overwriteClip(projectItem, position)",
  "track.insertClip(projectItem, position)",
  "",
  "## TrackItem (clip on timeline)",
  "clip.nodeId                    - String",
  "clip.name                      - String",
  "clip.start                     - Time (.ticks, .seconds)",
  "clip.end                       - Time",
  "clip.duration                  - Time",
  "clip.inPoint                   - Time (source in)",
  "clip.outPoint                  - Time (source out)",
  "clip.mediaType                 - String (\"Video\"/\"Audio\")",
  "clip.type                      - Number (1=clip, 2=transition)",
  "clip.projectItem               - ProjectItem (source)",
  "clip.components                - ComponentCollection (.numItems, [i])",
  "",
  "clip.remove(ripple, alignToVideo)",
  "clip.setSelected(selected, updateUI)",
  "clip.isSelected()              - Boolean",
  "clip.setDisabled(disabled)",
  "clip.isDisabled()              - Boolean",
  "clip.getSpeed()                - Number",
  "clip.isSpeedReversed()         - Boolean",
  "clip.isAdjustmentLayer()       - Boolean",
  "",
  "## Component (effects on clips)",
  "comp.displayName               - String",
  "comp.matchName                 - String",
  "comp.properties                - PropertyCollection (.numItems, [i])",
  "comp.remove()",
  "",
  "## Property (effect parameters)",
  "prop.displayName               - String",
  "prop.matchName                 - String",
  "prop.getValue(updateUI, time)",
  "prop.setValue(value, updateUI)",
  "prop.isTimeVarying()           - Boolean",
  "prop.setTimeVarying(enabled)",
  "prop.areKeyframesSupported()   - Boolean",
  "prop.getKeys()                 - Array of Time",
  "prop.addKey(time)",
  "prop.removeKey(time)",
  "prop.removeKeyRange(startTime, endTime)",
  "prop.getValueAtKey(time)",
  "prop.setValueAtKey(time, value, updateUI)",
  "prop.setInterpolationTypeAtKey(time, interpType, updateUI)",
  "prop.getValueAtTime(time)",
  "",
  "## Marker",
  "marker.name                    - String",
  "marker.comments                - String",
  "marker.start                   - Time",
  "marker.end                     - Time",
  "marker.type                    - String",
  "marker.createMarker(seconds)   - Marker",
  "marker.deleteMarker(marker)",
  "",
  "## Time Object",
  "var t = new Time();",
  "t.ticks = \"254016000000\";     - set time in ticks (string)",
  "t.seconds = 1.0;             - set time in seconds",
  "t.ticks                       - get ticks (string)",
  "",
  "## QE DOM (call app.enableQE() first!)",
  "qe.project.getActiveSequence()",
  "qe.project.getVideoEffectList()       - .numItems, [i].name",
  "qe.project.getAudioEffectList()       - .numItems, [i].name",
  "qe.project.getVideoTransitionList()   - .numItems, [i].name",
  "qe.project.getAudioTransitionList()   - .numItems, [i].name",
  "qe.project.getVideoEffectByName(name) - QEEffect",
  "",
  "qeSeq.getVideoTrackAt(index)          - QETrack",
  "qeSeq.getAudioTrackAt(index)          - QETrack",
  "qeTrack.getItemAt(index)              - QEClip",
  "qeTrack.razor(tickString)             - split at position",
  "",
  "qeClip.addVideoEffect(qeEffect)",
  "qeClip.addAudioEffect(qeEffect)",
  "qeClip.addTransition(qeTransition, forceSingle, durationTicks, endPercent, alignment)",
  "qeClip.removeEffects()",
  "qeClip.rippleDelete()",
  "qeClip.roll(offsetTicks)",
  "qeClip.slide(offsetTicks)",
  "qeClip.slip(offsetTicks)",
  "qeClip.setSpeed(percent)              - e.g., 200 for 2x",
  "qeClip.setReverse(bool)",
  "qeClip.setFrameBlend(bool)",
  "qeClip.setTimeInterpolationType(type) - 0=sampling, 1=blending, 2=optical flow",
  "qeClip.setName(name)",
  "qeClip.moveToTrack(trackIndex)",
  "",
  "## Constants",
  "TICKS_PER_SECOND = 254016000000",
  "",
  "## Common Effect Match Names",
  "\"AE.ADBE Motion\"           - Motion (Position, Scale, Rotation)",
  "\"AE.ADBE Opacity\"          - Opacity",
  "\"AE.ADBE Gaussian Blur 2\"  - Gaussian Blur",
  "\"AE.ADBE Black & White\"    - Black & White",
  "\"AE.ADBE Tint\"             - Tint",
  "\"AE.ADBE Motion Blur\"      - Motion Blur",
  "",
  "## Keyframe Interpolation Types",
  "KF_Interp_Mode_Linear = 0",
  "KF_Interp_Mode_Hold = 4",
  "KF_Interp_Mode_Bezier = 5",
].join("\n");
